In [17]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
df = pd.read_csv('nykaa_campaign_data.csv')
df.head()

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
0,NY-CMP-1000,Social Media,College Students,21,"WhatsApp, YouTube",57804,6156,3616,2355,1867515,111.03,6.14,Hindi,20.98,College Students,29-04-2025
1,NY-CMP-1001,Paid Ads,Tier 2 City Customers,18,YouTube,91801,3321,1971,1357,1046247,180.83,3.26,Hindi,7.24,College Students,06-04-2025
2,NY-CMP-1002,Influencer,Youth,23,"WhatsApp, Google, YouTube",15536,2182,952,755,197055,90.60,1.88,English,25.03,College Students,14-01-2025
3,NY-CMP-1003,Email,Working Women,18,"YouTube, Facebook, Instagram",88114,8413,2231,947,376906,249.07,0.60,Hindi,13.15,College Students,04-06-2025
4,NY-CMP-1004,Paid Ads,College Students,10,"Facebook, Instagram",96871,3743,2060,1258,518296,228.60,0.80,Hindi,7.29,Tier 2 City Customers,29-12-2024

In [19]:
df.shape

(55555, 16)

In [20]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55555 entries, 0 to 55554
Data columns (total 16 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Campaign_ID       55555 non-null  str
 1   Campaign_Type     55555 non-null  str
 2   Target_Audience   55555 non-null  str
 3   Duration          55555 non-null  int64
 4   Channel_Used      55555 non-null  str
 5   Impressions       55555 non-null  int64
 6   Clicks            55555 non-null  int64
 7   Leads             55555 non-null  int64
 8   Conversions       55555 non-null  int64
 9   Revenue           55555 non-null  int64
 10  Acquisition_Cost  55555 non-null  float64
 11  ROI               55555 non-null  float64
 12  Language          55555 non-null  str
 13  Engagement_Score  55555 non-null  float64
 14  Customer_Segment  55555 non-null  str
 15  Date              55555 non-null  str
dtypes: float64(3), int64(6), str(7)
memory usage: 6.8 MB

In [21]:
df.isnull().sum()

Campaign_ID         0
Campaign_Type       0
Target_Audience     0
Duration            0
Channel_Used        0
Impressions         0
Clicks              0
Leads               0
Conversions         0
Revenue             0
Acquisition_Cost    0
ROI                 0
Language            0
Engagement_Score    0
Customer_Segment    0
Date                0
dtype: int64

In [23]:
df.duplicated().sum()

np.int64(0)

In [24]:
df.describe()

,Duration,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Engagement_Score
count,55555.000000,55555.000000,55555.000000,55555.000000,55555.000000,5.555500e+04,55555.000000,55555.000000,55555.000000
mean,17.446044,55087.885357,4688.070507,1877.271119,1032.866925,5.158197e+05,377.347068,2.713807,13.784169
std,7.520438,25930.001514,3178.686285,1435.636117,862.496788,4.900121e+05,541.084524,4.493380,6.353125
min,5.000000,10001.000000,202.000000,56.000000,19.000000,6.183000e+03,9.080000,-0.970000,2.600000
25%,11.000000,32680.000000,2110.000000,779.000000,400.000000,1.777060e+05,105.435000,0.040000,8.360000
50%,17.000000,55182.000000,3907.000000,1481.000000,779.000000,3.604360e+05,207.510000,1.240000,13.600000
75%,24.000000,77514.500000,6688.000000,2605.000000,1414.000000,6.874225e+05,428.580000,3.630000,18.855000
max,30.000000,100000.000000,14868.000000,8876.000000,6686.000000,4.579910e+06,15473.160000,74.420000,30.910000

In [25]:
df.dtypes

Campaign_ID             str
Campaign_Type           str
Target_Audience         str
Duration              int64
Channel_Used            str
Impressions           int64
Clicks                int64
Leads                 int64
Conversions           int64
Revenue               int64
Acquisition_Cost    float64
ROI                 float64
Language                str
Engagement_Score    float64
Customer_Segment        str
Date                    str
dtype: object

In [30]:
df['Date'] = pd.to_datetime(df['Date'])

In [31]:
df[df['Acquisition_Cost'] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [32]:
df[df['Revenue'] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [33]:
df[df['Conversions'] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [35]:
df[df['Clicks'] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [36]:
df[df['Impressions'] < 0]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [39]:
df[df['ROI'] < 0]

,Campaign_ID,Campaign_Type,Target_Audience,Duration,Channel_Used,Impressions,Clicks,Leads,Conversions,Revenue,Acquisition_Cost,ROI,Language,Engagement_Score,Customer_Segment,Date
14,NY-CMP-1014,Paid Ads,Premium Shoppers,5,Instagram,38072,2591,1542,769,240697,369.75,-0.15,Bengali,12.88,College Students,2024-07-06
15,NY-CMP-1015,Paid Ads,Working Women,23,"Facebook, Instagram, Email",28714,1511,441,158,33654,1648.61,-0.87,Hindi,7.35,Premium Shoppers,2024-10-06
16,NY-CMP-1016,SEO,College Students,27,WhatsApp,73474,4886,2344,1055,263750,272.28,-0.08,English,11.28,College Students,2024-12-18
20,NY-CMP-1020,Paid Ads,Premium Shoppers,27,"Google, YouTube",10678,1217,524,163,111981,1124.19,-0.39,Bengali,17.83,Youth,2024-08-27
21,NY-CMP-1021,SEO,Working Women,22,"Instagram, YouTube, Google",27990,3508,761,385,155540,516.25,-0.22,Hindi,16.63,Youth,2025-01-30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
55533,NY-CMP-56533,Influencer,Tier 2 City Customers,28,"Instagram, Google",52672,2455,922,423,208116,605.91,-0.19,Tamil,7.21,Tier 2 City Customers,2024-12-08
55534,NY-CMP-56534,Email,Premium Shoppers,9,"Instagram, Google, YouTube",91610,2584,996,303,191799,974.90,-0.35,Tamil,4.24,College Students,2024-08-04
55544,NY-CMP-56544,SEO,College Students,10,Email,40817,3953,931,614,127712,422.69,-0.51,Hindi,13.47,College Students,2025-03-04
55546,NY-CMP-56546,SEO,Youth,24,"Instagram, YouTube",18658,686,219,102,58446,1897.64,-0.70,Tamil,5.40,Working Women,2024-07-16
55550,NY-CMP-56550,SEO,Youth,16,"Instagram, Email",31041,3849,1012,639,162945,374.90,-0.32,Tamil,17.72,Tier 2 City Customers,2025-02-16

In [40]:
df[df['Clicks'] > df['Impressions']]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [41]:
df[df['Conversions'] > df['Clicks']]

Empty DataFrame
Columns: [Campaign_ID, Campaign_Type, Target_Audience, Duration, Channel_Used, Impressions, Clicks, Leads, Conversions, Revenue, Acquisition_Cost, ROI, Language, Engagement_Score, Customer_Segment, Date]
Index: []

In [43]:
df.to_csv("nykaa_marketing_campaign_cleaning", index = False)